USE [master]
GO

/****** Object:  Database [DataTier.Net.Database]    Script Date: 11/8/2018 3:36:38 PM ******/
CREATE DATABASE [DataTier.Net.Database]
 CONTAINMENT = NONE
 ON  PRIMARY 
 -- Change to path to where you wish to install the database
( NAME = N'DataTier.Net.Database', FILENAME = N'C:\Data\DataTier.Net.Database.mdf' , SIZE = 4096KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'DataTier.Net.Database_log', FILENAME = N'C:\Data\DataTier.Net.Database_log.ldf' , SIZE = 1024KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [DataTier.Net.Database] SET COMPATIBILITY_LEVEL = 100
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [DataTier.Net.Database].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [DataTier.Net.Database] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [DataTier.Net.Database] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [DataTier.Net.Database] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [DataTier.Net.Database] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [DataTier.Net.Database] SET ARITHABORT OFF 
GO

ALTER DATABASE [DataTier.Net.Database] SET AUTO_CLOSE ON 
GO

ALTER DATABASE [DataTier.Net.Database] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [DataTier.Net.Database] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [DataTier.Net.Database] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [DataTier.Net.Database] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [DataTier.Net.Database] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [DataTier.Net.Database] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [DataTier.Net.Database] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [DataTier.Net.Database] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [DataTier.Net.Database] SET  DISABLE_BROKER 
GO

ALTER DATABASE [DataTier.Net.Database] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [DataTier.Net.Database] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [DataTier.Net.Database] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [DataTier.Net.Database] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [DataTier.Net.Database] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [DataTier.Net.Database] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [DataTier.Net.Database] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [DataTier.Net.Database] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [DataTier.Net.Database] SET  MULTI_USER 
GO

ALTER DATABASE [DataTier.Net.Database] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [DataTier.Net.Database] SET DB_CHAINING OFF 
GO

ALTER DATABASE [DataTier.Net.Database] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [DataTier.Net.Database] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [DataTier.Net.Database] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [DataTier.Net.Database] SET QUERY_STORE = OFF
GO

USE [DataTier.Net.Database]
GO

ALTER DATABASE SCOPED CONFIGURATION SET IDENTITY_CACHE = ON;
GO

ALTER DATABASE SCOPED CONFIGURATION SET LEGACY_CARDINALITY_ESTIMATION = OFF;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET LEGACY_CARDINALITY_ESTIMATION = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET MAXDOP = 0;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET MAXDOP = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET PARAMETER_SNIFFING = ON;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET PARAMETER_SNIFFING = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET QUERY_OPTIMIZER_HOTFIXES = OFF;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET QUERY_OPTIMIZER_HOTFIXES = PRIMARY;
GO

ALTER DATABASE [DataTier.Net.Database] SET  READ_WRITE 
GO


